using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class itemwithCategorySeedData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"INSERT INTO public.""ItemWithCategory""(""ItemId"", ""ItemCategoryId"", ""CreateDateTime"", ""ModifiedDateTime"")
                                                                                         VALUES(1, 1, CURRENT_DATE, null),
                                                                                               (1, 3, CURRENT_DATE, null),
                                                                                               (2, 1, CURRENT_DATE, null),
                                                                                               (2, 3, CURRENT_DATE, null),
                                                                                               (3, 1, CURRENT_DATE, null),
                                                                                               (3, 3, CURRENT_DATE, null),
                                                                                               (4, 1, CURRENT_DATE, null),
                                                                                               (4, 3, CURRENT_DATE, null),
                                                                                               (5, 1, CURRENT_DATE, null),
                                                                                               (5, 3, CURRENT_DATE, null),
                                                                                               (6, 1, CURRENT_DATE, null),
                                                                                               (6, 3, CURRENT_DATE, null),
                                                                                               (7, 1, CURRENT_DATE, null),
                                                                                               (7, 3, CURRENT_DATE, null),
                                                                                               (8, 1, CURRENT_DATE, null),
                                                                                               (8, 3, CURRENT_DATE, null),
                                                                                               (9, 1, CURRENT_DATE, null),
                                                                                               (9, 3, CURRENT_DATE, null),
                                                                                               (10, 1, CURRENT_DATE, null),
                                                                                               (10, 3, CURRENT_DATE, null),
                                                                                               (11, 1, CURRENT_DATE, null),
                                                                                               (11, 3, CURRENT_DATE, null),
                                                                                               (12, 1, CURRENT_DATE, null),
                                                                                               (12, 3, CURRENT_DATE, null),
                                                                                               (13, 1, CURRENT_DATE, null),
                                                                                               (13, 3, CURRENT_DATE, null),
                                                                                               (14, 1, CURRENT_DATE, null),
                                                                                               (14, 3, CURRENT_DATE, null),
                                                                                               (15, 1, CURRENT_DATE, null),
                                                                                               (15, 3, CURRENT_DATE, null),
                                                                                               (16, 1, CURRENT_DATE, null),
                                                                                               (16, 3, CURRENT_DATE, null),
                                                                                               (17, 1, CURRENT_DATE, null),
                                                                                               (17, 3, CURRENT_DATE, null),
                                                                                               (18, 1, CURRENT_DATE, null),
                                                                                               (18, 3, CURRENT_DATE, null),
                                                                                               (19, 1, CURRENT_DATE, null),
                                                                                               (19, 3, CURRENT_DATE, null),
                                                                                               (20, 1, CURRENT_DATE, null),
                                                                                               (20, 3, CURRENT_DATE, null),
                                                                                               (21, 1, CURRENT_DATE, null),
                                                                                               (21, 3, CURRENT_DATE, null),
                                                                                               (22, 1, CURRENT_DATE, null),
                                                                                               (22, 3, CURRENT_DATE, null),
                                                                                               (23, 1, CURRENT_DATE, null),
                                                                                               (23, 3, CURRENT_DATE, null),
                                                                                               (24, 1, CURRENT_DATE, null),
                                                                                               (24, 3, CURRENT_DATE, null),
                                                                                               (25, 1, CURRENT_DATE, null),
                                                                                               (25, 3, CURRENT_DATE, null),
                                                                                               (26, 1, CURRENT_DATE, null),
                                                                                               (26, 3, CURRENT_DATE, null),
                                                                                               (27, 1, CURRENT_DATE, null),
                                                                                               (27, 3, CURRENT_DATE, null),
                                                                                               (28, 1, CURRENT_DATE, null),
                                                                                               (28, 3, CURRENT_DATE, null),
                                                                                               (29, 1, CURRENT_DATE, null),
                                                                                               (29, 3, CURRENT_DATE, null),
                                                                                               (30, 1, CURRENT_DATE, null),
                                                                                               (30, 3, CURRENT_DATE, null),
                                                                                               (31, 1, CURRENT_DATE, null),
                                                                                               (31, 3, CURRENT_DATE, null),
                                                                                               (32, 1, CURRENT_DATE, null),
                                                                                               (32, 3, CURRENT_DATE, null),
                                                                                               (33, 1, CURRENT_DATE, null),
                                                                                               (33, 3, CURRENT_DATE, null),
                                                                                               (34, 1, CURRENT_DATE, null),
                                                                                               (34, 3, CURRENT_DATE, null),
                                                                                               (35, 1, CURRENT_DATE, null),
                                                                                               (35, 3, CURRENT_DATE, null),
                                                                                               (36, 1, CURRENT_DATE, null),
                                                                                               (36, 3, CURRENT_DATE, null),
                                                                                               (37, 1, CURRENT_DATE, null),
                                                                                               (37, 3, CURRENT_DATE, null),
                                                                                               (38, 1, CURRENT_DATE, null),
                                                                                               (38, 3, CURRENT_DATE, null),
                                                                                               (36, 1, CURRENT_DATE, null),
                                                                                               (36, 3, CURRENT_DATE, null),
                                                                                               (37, 1, CURRENT_DATE, null),
                                                                                               (37, 3, CURRENT_DATE, null),
                                                                                               (38, 1, CURRENT_DATE, null),
                                                                                               (38, 3, CURRENT_DATE, null),
                                                                                               (39, 1, CURRENT_DATE, null),
                                                                                               (39, 3, CURRENT_DATE, null),
                                                                                               (40, 1, CURRENT_DATE, null),
                                                                                               (40, 3, CURRENT_DATE, null),
                                                                                               (41, 1, CURRENT_DATE, null),
                                                                                               (41, 3, CURRENT_DATE, null),
                                                                                               (42, 1, CURRENT_DATE, null),
                                                                                               (42, 3, CURRENT_DATE, null),
                                                                                               (43, 1, CURRENT_DATE, null),
                                                                                               (43, 3, CURRENT_DATE, null),
                                                                                               (44, 2, CURRENT_DATE, null),
                                                                                               (45, 2, CURRENT_DATE, null),
                                                                                               (46, 2, CURRENT_DATE, null),
                                                                                               (47, 2, CURRENT_DATE, null),
                                                                                               (48, 2, CURRENT_DATE, null),
                                                                                               (49, 2, CURRENT_DATE, null),
                                                                                               (50, 2, CURRENT_DATE, null),
                                                                                               (51, 2, CURRENT_DATE, null),
                                                                                               (52, 2, CURRENT_DATE, null),
                                                                                               (53, 2, CURRENT_DATE, null),
                                                                                               (44, 1, CURRENT_DATE, null),
                                                                                               (45, 1, CURRENT_DATE, null),
                                                                                               (46, 1, CURRENT_DATE, null),
                                                                                               (47, 1, CURRENT_DATE, null),
                                                                                               (48, 1, CURRENT_DATE, null),
                                                                                               (49, 1, CURRENT_DATE, null),
                                                                                               (50, 1, CURRENT_DATE, null),
                                                                                               (51, 1, CURRENT_DATE, null),
                                                                                               (52, 1, CURRENT_DATE, null),
                                                                                               (53, 1, CURRENT_DATE, null);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
